### PR TITLE
WaylandBackend: allow gamescope to run under vulkan

### LINKED ISSUE #1604: Wayland/Vulkan: WaylandBackend.cpp:1568 Assertion `u8bitFormat != DRM_FORMAT_INVALID`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Launching gamescope on a Wayland compositor that's running with a Vulkan render crashes Gamescope and the following assert triggers:

```
gamescope: ../src/Backends/WaylandBackend.cpp:1568: virtual void gamescope::CWaylandBackend::GetPreferredOutputFormat(uint32_t*, uint32_t*) const: Assertion `u8BitFormat != DRM_FORMAT_INVALID' failed.
```

Doing a git bisect shows that 01101093445af20ea25ad386fd872d5f92266c2c is the bad commit.

__Workarounds__:
1. Using OpenGL as backend for the Wayland compositor
2. Using the SDL backend, requires #1548

__Compositor(s)__:
* Jay with Vulkan backend
* River with Vulkan backend
* River with OpenGL backend (works)

### Steps To Reproduce

1. Open terminal
2. Launch gamescope

### Hardware information

```markdown
- Distro: Arch Linux
- CPU: AMD 7735HS
- GPU0: Radeon 680M
- GPU1: Radeon RX 7600S
- Driver Version: mesa-git (24.3.0_devel.197058.e69aba2cded-1)
```

### Software information

```markdown
- Desktop environment: Jay + River
- Session type: Wayland
- Gamescope version: git upstream (3.15.9.r21.g7dd1bcd9-1)
- Gamescope launch command(s): n/a
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

Bisect log:
```
git bisect start
# status: waiting for both good and bad commits
# bad: [7dd1bcd9102a17e039970ccd9a324a9fe8365d6d] rendervulkan: Fix a CVulkanCmdBuffer leak that could result in screenshot request failures
git bisect bad 7dd1bcd9102a17e039970ccd9a324a9fe8365d6d
# status: waiting for good commit(s), bad commit known
# good: [b2505fe4dac917aadd1ab05473d863830a7b5859] Fix a CVulkanCmdBuffer leak that could result in screenshot request failures
git bisect good b2505fe4dac917aadd1ab05473d863830a7b5859
# good: [8045786067f7a7fd9fd3fff98c29588f314218a9] layer: Add hacks for Talos Principle and Serious Sam's bad swapchain usage
git bisect good 8045786067f7a7fd9fd3fff98c29588f314218a9
# bad: [ca7bf9ff4a1987f358a27c173d46fad7a4645658] readme: Fix Meson deprecated command warning
git bisect bad ca7bf9ff4a1987f358a27c173d46fad7a4645658
# bad: [d87f6d9b9d98ea8064e4063c01d483895fef87f0] Add clipboard support from SDL backend
git bisect bad d87f6d9b9d98ea8064e4063c01d483895fef87f0
# good: [7a273743368aaa6368cb0d31d4786d78b4b00dc6] rendervulkan: Fix scanout-able check
git bisect good 7a273743368aaa6368cb0d31d4786d78b4b00dc6
# bad: [a2b45e15009f80ca1ad346840f2574bbe060fa94] Fix how reshade effects are cleared
git bisect bad a2b45e15009f80ca1ad346840f2574bbe060fa94
# bad: [01101093445af20ea25ad386fd872d5f92266c2c] rendervulkan: Attempt at fixing modifierless devices having issues
git bisect bad 01101093445af20ea25ad386fd872d5f92266c2c
# first bad commit: [01101093445af20ea25ad386fd872d5f92266c2c] rendervulkan: Attempt at fixing modifierless devices having issues
```

### PR DESCRIPTION
**Pull request by mahkoh**
The invalid modifier is not supported under vulkan, so fall back to any other modifier if a format does not support the invalid modifier.

Closes #1604

### CODE REVIEW

**Comment by LaserEyess** [comment]
This fixes the issue for me.

**Comment by ninetailedtori** [comment]
Confirmed works flawlessly on my system as well. Can we get a merge PR?

**Comment by kode54** [comment]
Not sure this PR is entirely correct. At least under wlroots with the Vulkan backend, absolutely no formats report support for the INVALID modifier, only a bunch of tiled formats and LINEAR.

**Comment by mahkoh** [comment]
The original code is nonsense to begin with. To see if a format is supported you have to intersect what your upstream can produce with what your downstream can consume.

The goal of this PR was only to enable additional case that were previously definitely broken, therefore doing no harm. But gamescope seems unmaintained at this point.

File: src/Backends/WaylandBackend.cpp [hunk 1]
```diff
@@ -2002,24 +2002,32 @@ namespace gamescope
...
-        else if ( SupportsFormat( DRM_FORMAT_XBGR8888 ) )
-            u8BitFormat = DRM_FORMAT_XBGR8888;
-        else if ( SupportsFormat( DRM_FORMAT_ARGB8888 ) )
-            u8BitFormat = DRM_FORMAT_ARGB8888;
-        else if ( SupportsFormat( DRM_FORMAT_ABGR8888 ) )
-            u8BitFormat = DRM_FORMAT_ABGR8888;
+        for (int i = 0; i < 2 && u8BitFormat == DRM_FORMAT_INVALID; i++)
+        {
+            bool invalidOnly = i == 0;
+            if ( SupportsFormat( DRM_FORMAT_XRGB8888, invalidOnly ) )
```
Comment (emersion) [inline src/Backends/WaylandBackend.cpp:2008]: `SupportsFormat(format, false)` will always return true if `SupportsFormat(format, true)` returns true. In other words, I don't think we need to ever check `SupportsFormat(format, true)` here: checking whether the modifier list is non-empty should be enough.

File: src/backend.h [hunk 2]
```diff
@@ -309,9 +309,11 @@ namespace gamescope
 
         virtual bool UsesModifiers() const = 0;
         virtual std::span<const uint64_t> GetSupportedModifiers( uint32_t uDrmFormat ) const = 0;
-        inline bool SupportsFormat( uint32_t uDrmFormat ) const
+        inline bool SupportsFormat( uint32_t uDrmFormat, bool invalidOnly ) const
         {
-            return Algorithm::Contains( this->GetSupportedModifiers( uDrmFormat ), DRM_FORMAT_MOD_INVALID );
+            if ( invalidOnly )
+                return Algorithm::Contains( this->GetSupportedModifiers( uDrmFormat ), DRM_FORMAT_MOD_INVALID );
```
Comment (emersion) [inline src/backend.h:315]: I'd prefer to inline this line the only place where it's used, instead of adding a flag to make this function perform two different operations.

File: src/Backends/WaylandBackend.cpp (hunk 1 above)
Comment (mahkoh) [reply src/Backends/WaylandBackend.cpp:2008]: >SupportsFormat(format, false) will always return true if SupportsFormat(format, true) returns true.

That is so, however, if DRM_FORMAT_ARGB8888 supports the invalid modifier but DRM_FORMAT_XRGB8888 only supports explicit modifiers, then the old code and my patch will select DRM_FORMAT_ARGB8888. Whereas what you're suggesting would select DRM_FORMAT_XRGB8888.

Comment (emersion) [reply src/Backends/WaylandBackend.cpp:2008]: Why should the invalid modifier be preferred? It should be the other way around: explicit modifiers should be preferred when supported.

(Note, in practice formats will either all support implicit modifiers, or none.)

Comment (mahkoh) [reply src/Backends/WaylandBackend.cpp:2008]: >Why should the invalid modifier be preferred?

Why indeed. My goal for this PR was not to change the behavior in any case where gamescope already worked, only to enable new cases where gamescope would otherwise outright crash. So that the PR could get merged quickly.

Whoever authored SupportsFormat thought that checking for the invalid modifier explicitly instead of just checking if the list was not empty was important.

If you think it's fine, I can reduce this PR to a one-line patch that just changes how SupportsFormats works.

Comment (emersion) [reply src/Backends/WaylandBackend.cpp:2008]: I don't think the current behavior was entirely intentional, and since in practice it doesn't make a difference, I'd prefer simpler code and preferring explicit modifiers.

(I still think we should check for the invalid modifier in `vulkan_init_format()`, though.)

Comment (mahkoh) [reply src/Backends/WaylandBackend.cpp]: This should be done.

**Review by emersion — APPROVED** [review]
Thanks!
